import React from 'react';
import {
  Router,
  Wifi,
  Server,
  Monitor,
  Laptop,
  Smartphone,
  Printer,
  Shield,
  Database,
  Network,
  Radio,
  HardDrive,
  Box,
  // New icons
  Activity,
  Cpu,
  Key,
  Globe,
  Settings,
  Headphones,
  Terminal,
  Layers,
  Cloud,
  Usb,
  FileText,
  Tv,
  Briefcase,
  Users,
  Folder,
  Lock,
  Unlock,
  Phone,
  Mail,
  Bell,
  AlertTriangle,
  Search,
  CheckSquare,
  Calendar,
  CreditCard,
  Wrench,
  Disc,
  Eye,
  HelpCircle,
  Inbox,
  Plug,
  Power,
  Share2,
  Table,
  FileCode,
  Flame,
  Compass,
  BookOpen,
  Heart,
  UserCheck
} from 'lucide-react';
import { SystemTablesData } from '../types';

export const EQUIPMENT_ICONS_LIST = [
  { key: 'Router', label: 'Roteador', icon: Router },
  { key: 'Wifi', label: 'Wi-Fi / AP', icon: Wifi },
  { key: 'Server', label: 'Servidor', icon: Server },
  { key: 'Monitor', label: 'Computador / Monitor', icon: Monitor },
  { key: 'Laptop', label: 'Notebook', icon: Laptop },
  { key: 'Smartphone', label: 'Dispositivo Móvel', icon: Smartphone },
  { key: 'Printer', label: 'Impressora', icon: Printer },
  { key: 'Shield', label: 'Firewall / Segurança', icon: Shield },
  { key: 'Database', label: 'Banco de Dados', icon: Database },
  { key: 'Network', label: 'Switch / Rede', icon: Network },
  { key: 'Radio', label: 'Rádio / Antena', icon: Radio },
  { key: 'HardDrive', label: 'Storage / Disco', icon: HardDrive },
  { key: 'Box', label: 'Genérico / Caixa', icon: Box },
  // Expanded options
  { key: 'Activity', label: 'Desempenho / Monitoramento', icon: Activity },
  { key: 'Cpu', label: 'Cpu / Processador', icon: Cpu },
  { key: 'Key', label: 'Senha / Chave', icon: Key },
  { key: 'Globe', label: 'Website / Internet', icon: Globe },
  { key: 'Settings', label: 'Configurações / Ajustes', icon: Settings },
  { key: 'Headphones', label: 'Atendimento / Suporte', icon: Headphones },
  { key: 'Terminal', label: 'Console / Terminal', icon: Terminal },
  { key: 'Layers', label: 'Sistemas / Camadas', icon: Layers },
  { key: 'Cloud', label: 'Cloud / Nuvem', icon: Cloud },
  { key: 'Usb', label: 'Conexão USB / Pendrive', icon: Usb },
  { key: 'FileText', label: 'Documento / Relatório', icon: FileText },
  { key: 'Tv', label: 'Televisão / Painel', icon: Tv },
  { key: 'Briefcase', label: 'Negócios / Empresa', icon: Briefcase },
  { key: 'Users', label: 'Usuários / Equipe', icon: Users },
  { key: 'Folder', label: 'Pasta / Diretório', icon: Folder },
  { key: 'Lock', label: 'Bloqueado / Segurança', icon: Lock },
  { key: 'Unlock', label: 'Desbloqueado', icon: Unlock },
  { key: 'Phone', label: 'Telefone / Voip', icon: Phone },
  { key: 'Mail', label: 'E-mail / Mensagens', icon: Mail },
  { key: 'Bell', label: 'Notificação / Sino', icon: Bell },
  { key: 'AlertTriangle', label: 'Aviso / Alerta', icon: AlertTriangle },
  { key: 'Search', label: 'Pesquisa / Busca', icon: Search },
  { key: 'CheckSquare', label: 'Concluído / Tarefa', icon: CheckSquare },
  { key: 'Calendar', label: 'Calendário / Agenda', icon: Calendar },
  { key: 'CreditCard', label: 'Pagamento / Financeiro', icon: CreditCard },
  { key: 'Wrench', label: 'Ferramenta / Manutenção', icon: Wrench },
  { key: 'Disc', label: 'Mídia / CD / DVD', icon: Disc },
  { key: 'Eye', label: 'Visualização / Auditoria', icon: Eye },
  { key: 'HelpCircle', label: 'Ajuda / Dúvida', icon: HelpCircle },
  { key: 'Inbox', label: 'Entrada / Caixa de Entrada', icon: Inbox },
  { key: 'Plug', label: 'Cabo / Energia / Plugue', icon: Plug },
  { key: 'Power', label: 'Botão de Ligar', icon: Power },
  { key: 'Share2', label: 'Compartilhamento', icon: Share2 },
  { key: 'Table', label: 'Planilha / Cadastro', icon: Table },
  { key: 'FileCode', label: 'Arquivo de Código', icon: FileCode },
  { key: 'Flame', label: 'Urgência / Fogo', icon: Flame },
  { key: 'Compass', label: 'Orientação / GPS', icon: Compass },
  { key: 'BookOpen', label: 'Base de Conhecimento / Livro', icon: BookOpen },
  { key: 'Heart', label: 'Favorito / Saúde', icon: Heart },
  { key: 'UserCheck', label: 'Responsável Técnico', icon: UserCheck }
];

export function getEquipmentTypeIcon(tipoName?: string, systemTables?: SystemTablesData) {
  const tipoDef = systemTables?.tiposEquipamento?.find(
    (t) => t.nome.toLowerCase() === tipoName?.toLowerCase()
  );
  const iconKey = tipoDef?.icon || 'Box';
  const found = EQUIPMENT_ICONS_LIST.find((item) => item.key === iconKey);
  return found ? found.icon : Box;
}
